### ISSUE TITLE
Menu "Push notifications are off" tile does not redirect anywhere

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#271]
Environment : 
Pixel 3XL - Android v9 (BrowserStack), version v14

Scenario : 
- Make sure your phone has push notifications turned off for the app
- Open the app
- Open the menu

Issue : 
There is a tile "Push notifications are off" with an arrow on it indicating that clicking on this tile would redirect users somewhere but I cannot click on it (nothing happens on click). Not sure if this tile was supposed to redirect somewhere or not...

![bs_realdroid_Mobile_Google Pixel 3 XL-9 0-1440x2960](https://user-images.githubusercontent.com/47008295/85965053-6e866a80-b970-11ea-9cb3-5fe1d6c75af4.jpg)

**Comment by timarney** [comment]
From a fresh install during on boarding was the prompt to enable push notifications declined?

**Comment by JuliannaR** [comment]
@timarney yes, it was declined. But on old versions if you decline you cannot get it back. We might need to set up some regression testing around this.

**Comment by timarney** [comment]
@henrytao-me can you confirm what status comes back for this?  I think it's the blocked status.

**Comment by timarney** [comment]
https://github.com/CovidShield/mobile/issues/163

**Comment by henrytao-me** [comment]
Ah ha. I can take it. 👍

**Comment by timarney** [comment]
a) confirming the status gets updated

| Images    	| 1    	| 2    	| 3    	|   	|
|-----------	|------	|------	|------	|---	|
| Status    	|<img width="300" src="https://user-images.githubusercontent.com/62242/86542281-64211f00-bee2-11ea-94aa-e1f0ee14acda.png">	| <img width="300" src="https://user-images.githubusercontent.com/62242/86542279-64211f00-bee2-11ea-8545-3c5aab5cc12f.png"> 	| <img width="300" src="https://user-images.githubusercontent.com/62242/86542282-64b9b580-bee2-11ea-916f-7fe90bd3382a.png"> 	|   	|

**Comment by timarney** [comment]
@JuliannaR 

Tested on play store version - it took me here

<img width="400" src="https://user-images.githubusercontent.com/62242/86542598-e4488400-bee4-11ea-9b8a-0439801ffd5f.png">

**Comment by timarney** [comment]
@jpeersoxd can you confirm via a Play store install?

**Comment by timarney** [comment]
Looks like it's still an issue.

![Screenshot_20200705-181346](https://user-images.githubusercontent.com/62242/86543393-01cd1c00-beec-11ea-8e39-6e9f2220f406.png)

**Comment by timarney** [comment]
@JuliannaR - this needs to be tested.

**Comment by srepussard** [comment]
@timarney I can test this. Do we have a latest apk? or should I test via Play Store only

**Comment by timarney** [comment]
Play Store please :)

**Comment by timarney** [comment]
Any updates on the testing end for this?

**Comment by srepussard** [comment]
> Any updates on the testing end for this?

Unfortunately I couldn't test yet because I cannot get the latest app version from the Play Store :(

**Comment by henrytao-me** [comment]
@srepussard Try these steps to get latest build on Play Store. 

```
Force close the Google Play app
Open the Settings app
Go to Applications > Application Manager > Google Play Store > Storage
Click Clear Cache
Restart device (optional, sometime it works without restarting)
Open Google Play Store again and download the app
```

**Comment by JuliannaR** [comment]
@henrytao-me This how worked for 3 of 7 people I've tried to help today. The rest are stuck with the June 25th version of the app. Any other thoughts?

**Comment by henrytao-me** [comment]
Ah. They also need to accept the new invitation for internal test https://play.google.com/apps/internaltest/4700071260798507505

cc @JuliannaR @srepussard

**Comment by timarney** [comment]
I pushed a new build about 1hr ago - I was able to pull down the latest

**Comment by srepussard** [comment]
> I pushed a new build about 1hr ago - I was able to pull down the latest

I could download the latest app ! Testing now...

**Comment by srepussard** [comment]
Tested on Pixel 3A, Android 10, v25 : Passed
- Clicking on that "Push notifications are off" tile redirects user to the Covid Alert app settings

@timarney one quick question : after turning on push notifications from that screen and going back to the app, it seems that the new state is not directly updated. We still see "Notifications are off". We have to close the app and start it again to see it gone. Is this an issue? Let me know and I can log a separate ticket.

**Comment by timarney** [comment]
Think you just found this one.

https://github.com/cds-snc/covid-shield-mobile/issues/489

**Comment by srepussard** [comment]
Yep that's exactly the same issue. I'll close this one as Done. Thank you everybody !
